/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;

public class App {
    private final int LARGURA = 1000;
    private final int ALTURA = 600;
    Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(LARGURA, ALTURA);
        this.draw.setXscale(0, LARGURA);
        this.draw.setYscale(0, ALTURA);
        // ===============================================
        Grade tese = new Grade();
        tese.desenhar(draw);
        //=================================================

        Navio boat = new Navio();
        boat.desenhar(draw);
    }


    public static void main(String[] args) {
        App app = new App();
        app.draw.show();
        
    }
}



